inputs:
  solutionPath:
    required: true

  projectPath:
    required: true

  projectName:
    required: true

  githubToken:
    required: true

  GH_APP_ID:
    required: true

  GH_APP_PRIVATE_KEY:
    required: true

runs:
  using: "composite"

  steps:
    # - name: Obtain a GitHub App Installation Access Token
    #   id: githubAppAuth
    #   shell: bash
    #   run: |
    #     TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ inputs.githubToken }})"
    #     echo "MY_TOKEN=${TOKEN}" >> $GITHUB_ENV

    # # - name: Use the obtained token
    # #   shell: bash
    # #   run: |
    # #     curl -X POST -H 'Content-Type: application/json' \
    # #       -d '{"context":"test","state":"success"}' \
    # #       "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
    # #   env:
    # #     GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.GH_APP_ID }}
        private-key: ${{ inputs.GH_APP_PRIVATE_KEY }}

    - name: Use the token
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        gh api octocat

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependecnices
      run: dotnet restore ${{ inputs.solutionPath }}/*.sln
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.solutionPath }}/*.sln --no-restore --configuration release
      shell: bash

    # - name: Get version before
    #   shell: pwsh
    #   run: |
    #     $versionString = ([xml](Get-Content ${{ inputs.projectPath }})).Project.PropertyGroup.Version
    #     $version=[version]$versionString
    #     echo "VersionBefore=$versionString"

    - name: Install versionize
      if: github.ref == 'refs/heads/main'
      run: dotnet tool install --global Versionize
      shell: bash

    - name: Configure git user
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
      shell: bash

    - name: Run versionize
      if: github.ref == 'refs/heads/main'
      id: versionize
      run: |
        versionize --proj-name=${{ inputs.projectName }}
      shell: bash

    # - name: Get version after
    #   shell: pwsh
    #   run: |
    #     $versionString = ([xml](Get-Content ${{ inputs.projectPath }})).Project.PropertyGroup.Version
    #     $version=[version]$versionString
    #     echo "VersionAfter=$versionString"

    # - name: Git push tags
    #   shell: bash
    #   run: git push --tags

    - name: Publish to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet pack ${{ inputs.projectPath }} --output nuget-packages --configuration Release
        dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ inputs.githubToken }}
      shell: bash

    - name: Push changes to GitHub
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ steps.app-token.outputs.token }}
        branch: ${{ github.ref }}
        tags: true
        force: true
