# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Apps

on:
  push:
    branches: ["main"]
    paths:
      - "apps/CalculatorApp/**"

  pull_request:
    branches: ["main"]
    paths:
      - "apps/CalculatorApp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      projectPath: "apps/CalculatorApp/CalculatorApps.csproj"
      projectName: "CalculatorApp"
      projectVersion: "1.0.0"

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # for pushing GitHub Nuget packages
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Apps.sln

      - name: Build
        run: dotnet build Apps.sln --no-restore

      - name: Test
        run: dotnet test Apps.sln --no-build --verbosity normal

      - run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" --name "github" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet build Apps.sln --configuration Release
        shell: bash
      # secrets.gh_token
      - uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.projectName }}.${{ env.projectVersion }}',
              sha: context.sha
            })
