# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Calculator-Lib

on:
  push:
    branches: ["main"]
    paths:
      - "src/Calculator.Lib/**"

  pull_request:
    branches: ["main"]
    paths:
      - "src/Calculator.Lib/**"

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

env:
  solutionPath: "src/Calculator.Lib"
  projectPath: "src/Calculator.Lib/Calculator.Lib.csproj"

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Publish GitHub package
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish
        uses: ./.github/actions/publish-github-package
        with:
          solutionPath: ${{ env.solutionPath }}
          projectPath: ${{ env.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       projectPath: "src/Calculator.Lib/Calculator.Lib.csproj"
#       projectName: "Calculator.Lib"
#       projectVersion: "1.0.7"

#     permissions:
#       contents: write # to be able to publish a GitHub release
#       issues: write # to be able to comment on released issues
#       pull-requests: write # to be able to comment on released pull requests
#       id-token: write # to enable use of OIDC for npm provenance
#       packages: write # for pushing GitHub Nuget packages
#       actions: write

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: 9.0.x

#       - name: Restore dependencies
#         run: dotnet restore Libs.sln

#       - name: Build
#         run: dotnet build Libs.sln --no-restore

#       - name: Test
#         run: dotnet test Libs.sln --no-build --verbosity normal

#       - run: |
#           dotnet nuget add source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" --name "github" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
#           dotnet build Libs.sln --configuration Release
#           dotnet pack ${{ env.projectPath }} --output nuget-packages --configuration Release
#           dotnet nuget push **/*.nupkg --skip-duplicate -s "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
#         shell: bash
#       # secrets.gh_token
#       - uses: actions/github-script@v6.4.1
#         with:
#           script: |
#             github.rest.git.createRef({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               ref: 'refs/tags/${{ env.projectName }}.${{ env.projectVersion }}',
#               sha: context.sha
#             })
