# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Hello-Lib

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/Hello.Lib/**"

  pull_request:
    branches: ["main"]
    paths:
      - "src/Hello.Lib/**"

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

env:
  solutionPath: "src/Hello.Lib"
  projectPath: "src/Hello.Lib/Hello.Lib.csproj"
  projectName: "Hello.Lib"

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Publish GitHub package
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Build and Publish
        uses: ./.github/actions/publish-github-package
        with:
          solutionPath: ${{ env.solutionPath }}
          projectPath: ${{ env.projectPath }}
          projectName: ${{ env.projectName }}
          # githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubToken: ${{ secrets.PUSHCHANGESVERSIONIZE }}
